version: "3.1"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

#adding mango container
  mongo: #service name for mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=riwaj
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db #Named volume for data persistance
#adding redis container
  redis:
    image: redis
    

volumes:
  mongo-db: